name: swcify
type: node
up:
  - node:
      version: '12.21.0'
      yarn: true
  - rust:
      version: 'nightly-2021-08-12'
commands:
  __default__: build
  build:
    desc: 'Build the project'
    run: yarn run build
  test:
    desc: 'Run all the tests'
    run: yarn run test
  style:
    desc: 'run lint checks'
    run: yarn run lint
