on: push
name: JS tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.21'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build:ci
      - run: yarn test
